import type { PayrollHoursSummary } from './hoursAggregation';

export type PayrollExceptionType =
  | 'OPEN_SHIFT'
  | 'AUTO_CLOCK_OUT'
  | 'MISSED_PUNCH'
  | 'EDITED_SHIFT';

export type PayrollExceptionRow = {
  employeeId: number;
  employeeName: string;
  exceptionType: PayrollExceptionType;
  shiftStatus: 'COMPLETE' | 'OPEN' | 'UNMATCHED_OUT';
  date: string | null;
  clockInTimestamp: string | null;
  clockOutTimestamp: string | null;
  clockOutSource: string | null;
  adminTag: string | null;
  lastEditedAt: string | null;
  details: string;
};

export type PayrollExceptionReport = {
  rows: PayrollExceptionRow[];
  counts: Record<PayrollExceptionType, number>;
  totalCount: number;
};

function toLocalDayKey(timestamp: string | null) {
  if (!timestamp) {
    return null;
  }

  const date = new Date(timestamp);
  if (Number.isNaN(date.getTime())) {
    return null;
  }

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function buildPayrollExceptionReport(summary: PayrollHoursSummary): PayrollExceptionReport {
  const rows: PayrollExceptionRow[] = [];
  const counts: Record<PayrollExceptionType, number> = {
    AUTO_CLOCK_OUT: 0,
    EDITED_SHIFT: 0,
    MISSED_PUNCH: 0,
    OPEN_SHIFT: 0,
  };

  for (const employee of summary.shiftsByEmployee) {
    for (const shift of employee.shifts) {
      const baseRow = {
        adminTag: shift.adminTag,
        clockInTimestamp: shift.clockInTimestamp,
        clockOutSource: shift.clockOutSource,
        clockOutTimestamp: shift.clockOutTimestamp,
        date: toLocalDayKey(shift.clockInTimestamp ?? shift.clockOutTimestamp),
        employeeId: employee.employeeId,
        employeeName: employee.employeeName,
        lastEditedAt: shift.lastEditedAt,
        shiftStatus: shift.status,
      } as const;

      if (shift.status === 'OPEN') {
        rows.push({
          ...baseRow,
          details: 'Clock-in exists without a matching clock-out in this pay period.',
          exceptionType: 'OPEN_SHIFT',
        });
        counts.OPEN_SHIFT += 1;
      }

      if (shift.status === 'UNMATCHED_OUT') {
        rows.push({
          ...baseRow,
          details: 'Clock-out exists without a matching clock-in in this pay period.',
          exceptionType: 'MISSED_PUNCH',
        });
        counts.MISSED_PUNCH += 1;
      }

      if (shift.clockOutSource === 'AUTO') {
        rows.push({
          ...baseRow,
          details: 'Clock-out was generated by the auto clock-out process.',
          exceptionType: 'AUTO_CLOCK_OUT',
        });
        counts.AUTO_CLOCK_OUT += 1;
      }

      if (shift.adminTag === 'EDITED' || shift.adminTag === 'CREATED') {
        rows.push({
          ...baseRow,
          details:
            shift.adminTag === 'CREATED'
              ? 'Shift was created manually by an admin.'
              : 'Shift was edited manually by an admin.',
          exceptionType: 'EDITED_SHIFT',
        });
        counts.EDITED_SHIFT += 1;
      }
    }
  }

  rows.sort(
    (a, b) =>
      a.employeeName.localeCompare(b.employeeName) ||
      (a.clockInTimestamp ?? a.clockOutTimestamp ?? '').localeCompare(
        b.clockInTimestamp ?? b.clockOutTimestamp ?? '',
      ) ||
      a.exceptionType.localeCompare(b.exceptionType),
  );

  return {
    counts,
    rows,
    totalCount: rows.length,
  };
}
